### ISSUE TITLE
How to start the project with 'ng serve' ?

### ISSUE THREAD

**Issue by xerZV** [AnkitSharma-007/angular-i18n-localization#1]
How to start the project with 'ng serve' ?

**Comment by AnkitSharma-007** [comment]
Please refer to https://ankitsharmablogs.com/localization-in-angular-using-i18n-tools/

I have shown the step by step process of creating this application and how to execute it in local environment using `ng serve`

**Comment by xerZV** [comment]
Yeah but my question is how to start the project with working i18n using ng serve.
In your article you show how to start only one config, not both of the langs

**Comment by AnkitSharma-007** [comment]
To execute the application in your local machine you need to use one config at a time such as `ng serve --configuration=es` for Spanish language. If you want to run for Hindi language then use `ng serve --configuration=hi`. The configuration should be specified in `angular.json` file. In the article i have explained how to add configuration for `es`, you can add similarly for other languages.

**Comment by xerZV** [comment]
Yeah, but im asking is there any way to run the app local with ng serve for the two configs. In Angular JS there was a way to have i18n with more than one lang at a time
